### ISSUE TITLE
Rust 2018 update causing V3Sender to result in 415 response

### ISSUE THREAD

**Issue by leanrob** [gsquire/sendgrid-rs#36]
When updating a project to Rust 2018, a previously working sendgrid email setup returns a 415 StatusCode (Unsupported Media Type).

When using sendgrid-rs 0.7.2 the the V3Sender content-type header looks like...

```
headers.insert(
    header::CONTENT_TYPE,
    HeaderValue::from_static("application/x-www-form-urlencoded"),
);
```
However, the master branch has changed the content type to `application/json` which causes the emails to send correctly.

It looks like the master branch can be deployed as it is?

**Comment by gsquire** [comment]
Thanks for reporting this and sorry for the regression!

I can't push master up quite yet since there are some breaking changes in flight. However I can make the fix on the branch I made 0.7.2 with and bump it to 0.7.3.

I will be able to do this toward the end of the day and will update it here when I am done.

**Comment by gsquire** [comment]
I uploaded a [patch](https://crates.io/crates/sendgrid/0.7.3) for this bug. Please feel free to open another issue if you find one.

Thanks again!

**Comment by leanrob** [comment]
Thanks for the quick response on that @gsquire !

Glad to see the fix in. Will be testing it out soon.
